"""Images and Audio Required

Revision ID: db450cf63dba
Revises: 05d667976d75
Create Date: 2025-11-29 10:44:29.962305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db450cf63dba'
down_revision = '05d667976d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.alter_column('cover_image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musics', schema=None) as batch_op:
        batch_op.alter_column('cover_image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
